services:
  - type: web
    name: buspass_project
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn buspass_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: buspass_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 4